services:
  db:
    image: postgres:16
    container_name: work-postgres
    environment:
      POSTGRES_DB: workdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - work_db_data:/var/lib/postgresql/data

  work-service:
    image: arifruette/work-service:0.0.1
    build: .
    container_name: work-service
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  work_db_data:
